version: '2'

services:

  orderer.energy-credit.com:
    container_name: orderer.energy-credit.com
    image: ${FABRIC_ORDERER_FIXTURE_IMAGE}:${FABRIC_ORDERER_FIXTURE_TAG}
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/energy-credit.com/orderers/orderer.energy-credit.com/msp:/var/hyperledger/orderer/msp
    - ./crypto-config/ordererOrganizations/energy-credit.com/orderers/orderer.energy-credit.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
      
  peer0.org1.energy-credit.com:
    container_name: peer0.org1.energy-credit.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.energy-credit.com
      - CORE_PEER_ADDRESS=peer0.org1.energy-credit.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.energy-credit.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.energy-credit.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.energy-credit.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCHDB_U}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCHDB_PSW}
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.energy-credit.com/peers/peer0.org1.energy-credit.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.energy-credit.com/peers/peer0.org1.energy-credit.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
  
  peer1.org1.energy-credit.com:
    container_name: peer1.org1.energy-credit.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.energy-credit.com
      - CORE_PEER_ADDRESS=peer1.org1.energy-credit.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.energy-credit.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.energy-credit.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.org1.energy-credit.com:8051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCHDB_U}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCHDB_PSW}
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.energy-credit.com/peers/peer1.org1.energy-credit.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.energy-credit.com/peers/peer1.org1.energy-credit.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:8051

  peer2.org1.energy-credit.com:
    container_name: peer2.org1.energy-credit.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer2.org1.energy-credit.com
      - CORE_PEER_ADDRESS=peer2.org1.energy-credit.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer2.org1.energy-credit.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.energy-credit.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer2.org1.energy-credit.com:9051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=${COUCHDB_U}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=${COUCHDB_PSW}
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.energy-credit.com/peers/peer2.org1.energy-credit.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.energy-credit.com/peers/peer2.org1.energy-credit.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:9051
  
  couchdb0:
    container_name: couchdb0
    image: ${FABRIC_COUCHDB_FIXTURE_IMAGE}:${FABRIC_COUCHDB_FIXTURE_TAG}
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=${COUCHDB_U}
      - COUCHDB_PASSWORD=${COUCHDB_PSW}
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
  
  couchdb1:
    container_name: couchdb1
    image: ${FABRIC_COUCHDB_FIXTURE_IMAGE}:${FABRIC_COUCHDB_FIXTURE_TAG}
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=${COUCHDB_U}
      - COUCHDB_PASSWORD=${COUCHDB_PSW}
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "6984:5984"
  
  couchdb2:
    container_name: couchdb2
    image: ${FABRIC_COUCHDB_FIXTURE_IMAGE}:${FABRIC_COUCHDB_FIXTURE_TAG}
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=${COUCHDB_U}
      - COUCHDB_PASSWORD=${COUCHDB_PSW}
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "8984:5984"