version: '2'

networks:
    virgo:

services:

    ca1:
        image: ${FABRIC_CA_FIXTURE_IMAGE}:${FABRIC_CA_FIXTURE_TAG}
        environment:
         - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
         - FABRIC_CA_SERVER_CA_NAME=ca-org1
        #  - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.energy-credit.com-cert.pem
        #  - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${FABRIC_CA_SERVER_ORG1_CA_KEYFILE}
         - FABRIC_CA_SERVER_TLS_ENABLED=true
         - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.energy-credit.com-cert.pem
         - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${FABRIC_CA_SERVER_ORG1_CA_KEYFILE}
        ports:
          - "7054:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.energy-credit.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${FABRIC_CA_SERVER_ORG1_CA_KEYFILE} -b admin:adminpw -d'
        volumes:
          - ./crypto-config/peerOrganizations/org1.energy-credit.com/ca/:/etc/hyperledger/fabric-ca-server-config
          # - ./cas/ca1/:/etc/hyperledger/fabric-ca-server
        container_name: ca1
        networks:
          - virgo